Repository daviderestivo/homebrew-emacs-head, pull requests merged in 2020-12, with the labels that each got.

#71 Update macOS Catalina emacs-head@27 bottle
  Formula/emacs-head@27.rb
Labels: bug

#72 Add Big Sur bottles
  Formula/emacs-head@26.rb
  Formula/emacs-head@27.rb
  README.org
Labels: enhancement

#73 include patches for Apple Silicon
  Formula/emacs-head@27.rb
  patches/0009-arm.patch
Labels: enhancement

#74 Various enhancement and bug fixes
  .github/workflows/emacs-26.yml
  .github/workflows/emacs-27.yml
  .github/workflows/emacs-28.yml
  .github/workflows/emacs.yml
  Formula/emacs-head@26.rb
  Formula/emacs-head@27.rb
  Formula/emacs-head@28.rb
Labels: bug, enhancement

#77 Fix https://github.com/daviderestivo/homebrew-emacs-head/issues/75
  Formula/emacs-head@27.rb
  Formula/emacs-head@28.rb
Labels: bug

#78 Emacs 27 ARM patch needs to be applied only to stable and not to head
  .github/workflows/emacs-27.yml
  Formula/emacs-head@26.rb
  Formula/emacs-head@27.rb
  Formula/emacs-head@28.rb
Labels: bug

#79 Feature/native comp
  .github/workflows/emacs-28.yml
  Formula/emacs-head@28.rb
  README.org
  patches/0009-Native-comp-env-setup.patch
Labels: enhancement

#82 Update native-comp-env-setup patch
  Formula/emacs-head@27.rb
  Formula/emacs-head@28.rb
  patches/0009-Native-comp-env-setup-absolute.patch
  patches/0010-Arm.patch
  patches/0011-Executables-codesign.patch
Labels: bug, enhancement

#83 Add Xcode CLI tools lib directory to runtime LIBRARY_PATH (Big Sur)
  Formula/emacs-head@28.rb
  patches/0009-Native-comp-env-setup-absolute.patch
Labels: enhancement

#84 Remove native-comp patch and add Dependabot
  .github/dependabot.yml
  Formula/emacs-head@28.rb
  patches/0009-Native-comp-env-setup-absolute.patch
Labels: enhancement

#86 Bump actions/checkout from v1 to v2.3.4
  .github/workflows/emacs-26.yml
  .github/workflows/emacs-27.yml
  .github/workflows/emacs-28.yml
  .github/workflows/emacs.yml
Labels: dependencies
