Repository daviderestivo/homebrew-emacs-head, pull requests merged in 2021-11, with the labels that each got.

#135 Remove forgotten xcode version selection
  .github/workflows/emacs.yml
Labels: enhancement

#138 Point out that Pdumper won't work with Native-comp support.
  README.org
Labels: enhancement, good first issue

#139 Remove unnecessary CFLAGS
  Formula/emacs-head@28.rb
  Formula/emacs-head@29.rb
Labels: enhancement

#140 Stop using brew test
  .github/workflows/emacs-26.yml
  .github/workflows/emacs-27.yml
  .github/workflows/emacs-28.yml
  .github/workflows/emacs-29.yml
Labels: ci
