Repository daviderestivo/homebrew-emacs-head, pull requests merged in 2021-04, with the labels that each got.

#107 Fix arm patch
  Formula/emacs-head@27.rb
  patches/0010-Arm.patch
Labels: bug, enhancement

#110 Fix native-comp .eln file globbing
  Formula/emacs-head@28.rb
Labels: bug

#112 Link to the original author of modern-icon-black-dragon.
  README.org
Labels: enhancement, good first issue

#111 Change --with-native-comp to use master
  Formula/emacs-head@28.rb
Labels: enhancement, good first issue
