Repository daviderestivo/homebrew-emacs-head, pull requests merged in 2025-02, with the labels that each got.

#236 Remove BLOCK_ALIGN patch for emacs-head@31
  Formula/emacs-head@31.rb
  patches/0012-BLOCK_ALIGN.patch
Labels: fix

#237 Expose macOS native sharing dialog via ns-share
  Formula/emacs-head@30.rb
  Formula/emacs-head@31.rb
  patches/0013-Native-sharing.patch
Labels: enhancement

#238 Bump emacs-head@30 to 30.1-rc1
  Formula/emacs-head@30.rb
Labels: enhancement

#239 Update README file
  README.org
Labels: documentation

#240 Update to Emacs 30.1 release
  Formula/emacs-head@30.rb
  README.org
Labels: enhancement
